### ISSUE TITLE
[bug]: Selfhosting Docker Install. Changing Container Name and Port

### ISSUE THREAD

**Issue by techguruagi** [makeplane/plane#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've several other containers running and one of the container is using "redis" as the name. Also running in the same port.  same is the case with pgsql. 

If i change the container name to planeredis and port to 6380, redis is not getting connected. 

What should i do ?. 

### Steps to reproduce

In docker-compose-hub.yml

redis:
    image: redis:6.2.7-alpine
    container_name: planeredis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redisdata:/data

### Browser

Google Chrome

### Version

Selfhost

**Comment by me-abhishekpal** [comment]
It is not working on a fresh install too. Not able to change any ports.
It does not connect with either planebackend, planerqworker.

**Comment by pablohashescobar** [comment]
Hello, @techguruagi! Considering that the container names have been changed, it's likely that the hostnames to the containers have also been altered. To resolve this issue, I recommend updating the `REDIS_URL` environment variable in both the plane-api and plane-worker containers to `redis://<HOSTNAME>:6379/` By doing so, it should resolve the problem, and the applications should start functioning correctly again.

**Comment by me-abhishekpal** [comment]
Hey @pablohashescobar 

for the record, i got the same error and I tried replacing the URLs accross the containers. Redis starts working but the plane worker and plane backend are still do not connect.

**Comment by pablohashescobar** [comment]
Hello @techguruagi! We're excited to inform you that we have updated the Docker setup. It would be fantastic if you could give it a try with the new setup. In this update, we have renamed `redis` to `plane-redis` for better clarity and organization. If you encounter any issues or have any questions during the process, please don't hesitate to reach out.

**Comment by techguruagi** [comment]
Hi @pablohashescobar 

Thank you. Installed the latest instance and is working fine. Appreciate your support

**Comment by pablohashescobar** [comment]
Thanks for the update @techguruagi. Closing this issue now.
