### ISSUE TITLE
[bug]: Image asset url issue with custom port

### ISSUE THREAD

**Issue by siunus** [makeplane/plane#2661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I run plane using a custom nginx port on localhost
`NGINX_PORT=8091`

I tried to change my profile picture, but it didn't appear. I inspected the element and saw that the image URL was incorrect.
The image URL should be like this `http://localhost:8091/uploads/user-387a...`
I tried accessing it directly using the correct URL, and the image appeared.

### Steps to reproduce

![image](https://github.com/makeplane/plane/assets/42384452/94d19fc7-bd32-4a55-9459-63a7c9281e52)

![image](https://github.com/makeplane/plane/assets/42384452/52477e6d-4ec9-463a-988e-e9d977dc0929)

### Browser

Google Chrome

### Version

Local

**Comment by MFYDev** [comment]
same issue here, checked everywhere but all image url will be localhost

**Comment by pablohashescobar** [comment]
Hi,
Can you configure the variable `WEB_URL` in `apiserver/.env` to the value of your current hosted url `http://localhost:8091`

**Comment by MFYDev** [comment]
@pablohashescobar Hi, I actually already set it. But running `docker compose -f docker-compose-hub.yml up -d` still will make the image url like that

**Comment by pablohashescobar** [comment]
Got it @MFYDev, this looks like a bug I will report this to the internal team and fix it as soon as possible thank you for reporting this.

**Comment by jandoerntlein** [comment]
> Hi, Can you configure the variable `WEB_URL` in `apiserver/.env` to the value of your current hosted url `http://localhost:8091`

This actually fixes the bug. 

Weird thing however: WEB_URL was not set at all in the beginning. Not even to http://localhost or something else by default. It seems that no environment variable set in ./apiserver/.env was realised at all.

**Comment by pablohashescobar** [comment]
You are correct this is a bug it is fixed in the current `develop` branch. For now you can add the variable `WEB_URL` for the backend container.

**Comment by olivierlambert** [comment]
Hi,

Having the same issue (serving on `localhost:8080`) but I'm using the `plane-app-preview` system with the `setup.sh` to handle the Docker containers. I don't know where to find the `apiserver` path to edit the `.env` file and fixing the issue.

**Comment by pablohashescobar** [comment]
Hey @olivierlambert you have to update the value of `WEB_URL`  in the `.env`

**Comment by olivierlambert** [comment]
I did this:

```
NGINX_PORT=8080
WEB_URL=http://localhost:8080
```

But I still have any uploaded picture (like an avatar) 404'ing because it's pointing to `http://localhost/uploads…` instead of the public URL (which is defined at `NEXT_PUBLIC_DEPLOY_URL`). Maybe I'm missing something? (I have my own nginx as a reverse proxy elsewhere)

**Comment by pablohashescobar** [comment]
`WEB_URL`  should be configured to your `http://current domain`

**Comment by olivierlambert** [comment]
Ah indeed, it did the trick! Thank you very much for:
1. being ultra fast to answer
2. while being helpful

And kudos on the project BTW, keep up the great work!

**Comment by vihar** [comment]
@pablohashescobar, can we close this issue?

**Comment by pablohashescobar** [comment]
Yeah @vihar

**Comment by olivierlambert** [comment]
Hmm wait, it seems that after few restart with the `setup.sh` it didn't work anymore :thinking: 

I don't have anything listening on the port 8080 on this machine. Could it be possible because this machine is NOT doing the SSL termination and not being the machine currently at this URL name?

In short, I have a dedicated Nginx VM with the SSL and domain name, acting as a reverse proxy for the other VM with Plane.

It's like when the `.env` is really taken into account, the URL can't be bound anymore with the public URL and only localhost :thinking: 

Sorry I'm not really used to Docker, it's probably something trivial that I'm missing.

**Comment by olivierlambert** [comment]
Wow, it's weird. It's like the plane-proxy container was not started initially on boot.

**Comment by vihar** [comment]
@olivierlambert, hope this issue is now fixed. Closing now. 🍰

**Comment by olivierlambert** [comment]
It is fixed, thanks!
