### ISSUE TITLE
[bug]: unnecessary new line on click at the end of a document

### ISSUE THREAD

**Issue by ZaLiTHkA** [makeplane/plane#6876]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

while editing a "Page" in any project, clicking anywhere below the last line sometimes causes the editor to insert an additional blank line.

a few points that make this feel less like "intended behaviour" and more like a bug:

- the "grab handle" visible to the left of the line before clicking does not shift down to the new line when the cursor appears.
- this does not happen if the cursor is currently on any other empty line, even if that line is much further up the page.

based on the typical behaviour of other editors, I would expect clicking anywhere below existing document content would simply move my cursor to the end of that content, not create a new line below it..

### Steps to reproduce

simplest reproduction:
 
1. create a new page in any project
2. add some placeholder text
3. click anywhere below the content - **new line created**

more complex reproduction:

1. create a new page in any project
2. add 2 paragraphs of placeholder text
3. move cursor to the end of the first paragraph and press "Enter"
4. click anywhere below the content - **no new line created**
5. move cursor to either first or second paragraph
6. click anywhere below the content - **new line created**
7. move cursor to first empty line below last paragraph
8. click anywhere below the content - **no new line created**

### Environment

Production

### Browser

Google Chrome

### Variant

Cloud

### Version

v0.25.3

**Comment by ZaLiTHkA** [comment]
quick note: I did clone the workspace and have a quick look through the `packages` folder in this monorepo, but I am currently at work so I haven't dug too deep into any of it as yet..

if someone is able to at least point me towards the appropriate package that handles this (`packages/editor` perhaps?), I would gladly see if I can fix it myself and send a PR.

**Comment by pushya22** [comment]
Hi @ZaLiTHkA This is issue has been resolved in our latest release. Please upgrade to v0.26.0

**Comment by ZaLiTHkA** [comment]
> Hi [@ZaLiTHkA](https://github.com/ZaLiTHkA) This is issue has been resolved in our latest release. Please upgrade to v0.26.0

apologies for the delayed response, I only just noticed this message now...

I've been using the browser version of Plane exclusively, so there was nothing to "upgrade" in that sense. however, the problem I reported still exists. also just installed the desktop client on my MacBook M1 now to test (running macOS 15.4.1) and I see the exact same issue there as well.

not really sure how to tie in either of these clients with the version numbers mentioned here though, as help menu popup at the bottom of the sidebar simply shows "Version: latest" in both the web UI and the macOS desktop client, whereas the "About Plane" menu entry from my desktop client shows version `1.5.1`.

---

would it perhaps help if I share a video of the issue in action? it's not difficult to reproduce, but trying to explain it as I did initially does get a little verbose.

**Comment by ZaLiTHkA** [comment]
FWIW, this may not be limited to the "Pages" feature, as this same behaviour can be seen while editing the description of "Work Items" in a project.

**Comment by Palanikannan1437** [comment]
Hey @ZaLiTHkA, thanks for bringing this into our notice and for the detailed reproduction, we missed an edge case while solving this!
