### ISSUE TITLE
[bug]: When sub-groups enabled, scrollbar size in Kanban view does not account for the Labels dropdown, maybe others

### ISSUE THREAD

**Issue by Wizzerinus** [makeplane/plane#7293]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

Sometimes, at the bottom of the Kanban view, the Labels dropdown is facing downwards from the work item instead of upwards, which means the labels cannot be set.

This seems to be related to #4019, though I am opening a new issue as that one is closed.

![Image](https://github.com/user-attachments/assets/85c8a81f-c6fc-4db9-9d74-bc258501409d)

Major usability problem due to #7294 

### Steps to reproduce

I am not sure if this always gets reproduced like this but:

1. Have a lot of items on the Kanban view. It seems to be easier reproduced with **sub-groups enabled**. Though I am not fully sure.
2. Try to set a label

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.26.1

**Comment by pushya22** [comment]
Hi @Wizzerinus This issue is already fixed and it will be part of our upcoming release.

**Comment by Wizzerinus** [comment]
Fair enough!

**Comment by pushya22** [comment]
Hi @Wizzerinus 

Kindly upgrade to our latest version v0.27.0. Please let us know if the issue persists after the update.

**Comment by Wizzerinus** [comment]
Will try. Thanks!

**Comment by Wizzerinus** [comment]
Hi again @pushya22 !

I've tried upgrading to 0.27.0 and it seems my issue is not fixed.

Specifically, it looks like the UI sets the top half of items to create the dropdown downwards, and another half to create it upwards. If after the sub-groups there is only 1 item in some category, it will always dropdown downwards as it is considered in the top half. Thus, it will have this bug if it's also the bottom sub-group. A screenshot of what I mean is attached.

There is also a behavior where this top/bottom assignment only is computed when the page is reloaded and not when items are moved around, though I do not think myself it is a huge deal.

![Image](https://github.com/user-attachments/assets/45a5e3ae-6325-4b21-afef-2941bdf74f79)

**Comment by pushya22** [comment]
Hi @Wizzerinus It appears that our earlier resolution did not fully address the issue. We’ve identified the root cause and will be pushing a fix immediately. Thank you for your patience.
